# Generated by Django 5.2.8 on 2025-12-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_savedaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaccount',
            name='account_title',
            field=models.CharField(default='site', max_length=256),
            preserve_default=False,
        ),
    ]
