# Generated by Django 5.2.8 on 2025-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaccount',
            name='encrypted_username_or_email',
        ),
        migrations.AddField(
            model_name='savedaccount',
            name='username_or_email',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
    ]
