# Generated by Django 5.2.8 on 2025-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0005_remove_savedaccount_encrypted_username_or_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='master_password_hash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedaccount',
            name='encrypted_password',
            field=models.JSONField(),
        ),
    ]
