# Generated by Django 5.2.8 on 2025-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0006_userprofile_master_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cipher_text',
            field=models.CharField(default='q', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iterations',
            field=models.IntegerField(default=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iv',
            field=models.CharField(default='q', max_length=255),
            preserve_default=False,
        ),
    ]
