# Generated by Django 5.2.8 on 2025-12-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0007_userprofile_cipher_text_userprofile_iterations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='master_password_hash',
        ),
    ]
