# Generated by Django 5.2.8 on 2025-12-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0008_remove_userprofile_master_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaccount',
            name='key_salt',
        ),
    ]
