# Generated by Django 5.2.8 on 2025-12-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0009_remove_savedaccount_key_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedaccount',
            name='encrypted_password',
            field=models.CharField(max_length=256),
        ),
    ]
