# Generated by Django 5.2.8 on 2025-12-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0010_alter_savedaccount_encrypted_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedaccount',
            old_name='username_or_email',
            new_name='encrypted_username_or_email',
        ),
    ]
