# Generated by Django 5.2.8 on 2025-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0011_rename_username_or_email_savedaccount_encrypted_username_or_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaccount',
            name='iv',
        ),
        migrations.AddField(
            model_name='savedaccount',
            name='password_iv',
            field=models.CharField(default='text', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedaccount',
            name='username_or_email_iv',
            field=models.CharField(default='text', max_length=256),
            preserve_default=False,
        ),
    ]
