# Generated by Django 5.2.8 on 2025-12-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0012_remove_savedaccount_iv_savedaccount_password_iv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaccount',
            name='encrypted_additional_data',
            field=models.CharField(default='blank', max_length=2000),
            preserve_default=False,
        ),
    ]
