# Generated by Django 5.2.8 on 2025-12-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0013_savedaccount_encrypted_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaccount',
            name='additional_data_iv',
            field=models.CharField(default='blank', max_length=256),
            preserve_default=False,
        ),
    ]
